### ISSUE TITLE
230518 청주 버스 시간표 수정

### ISSUE THREAD

**Issue by Invidam** [BCSDLab/KOIN_BATCH#23]
https://portal.koreatech.ac.kr/ctt/bb/bulletin?dm=pr&b=14&p=30665

참고: #22

**Comment by tmdgus1715** [comment]
**바꾼 내용**
청주 하교 셔틀 5회차(목/금) 시간 변경


**파일 명(stage)**
cheongju_shuttle.yaml

**변경 전**
```
 - route_name: "22시 00분"
    running_days: ["THU", "FRI"]
    arrival_info:
      - node_name: *koreatech
        arrival_time: "22:10"
      - node_name: *oc_science_park
        arrival_time: "하차"
      - node_name: *sm_hospital
        arrival_time: "하차"
      - node_name: *sb_four
        arrival_time: "하차"
      - node_name: *bongmyoung_four
        arrival_time: "하차"
      - node_name: *sc_four
        arrival_time: "하차"
      - node_name: *gym
        arrival_time: "종점"
```
**변경 후** 
<br>
```
 - route_name: "22시 10분"
    running_days: ["THU", "FRI"]
    arrival_info:
      - node_name: *koreatech
        arrival_time: "22:10"
      - node_name: *oc_science_park
        arrival_time: "하차"
      - node_name: *sm_hospital
        arrival_time: "하차"
      - node_name: *sb_four
        arrival_time: "하차"
      - node_name: *bongmyoung_four
        arrival_time: "하차"
      - node_name: *sc_four
        arrival_time: "하차"
      - node_name: *gym
        arrival_time: "종점"
```
