### ISSUE TITLE
230621 등하교 버스 시간 변경

### ISSUE THREAD

**Issue by daheeParkk** [BCSDLab/KOIN_BATCH#25]
기존 :
https://www.koreatech.ac.kr/kor/CMS/NoticeMgr/view.do?mCode=MN230&post_seq=30591&board_id=14
변경 :
https://www.koreatech.ac.kr/kor/CMS/NoticeMgr/view.do?mCode=MN230&post_seq=30808&board_id=14

**Comment by songsunkook** [comment]
### 천안 셔틀 운행 정보 변경
- **기존 운행 정보를 모두 주석 처리** (대부분의 운행이 중단됨)
- 기존 비슷한 운행 정보를 토대로 운행 정보를 추가
- 신규 운행 정류장 노드 추가

Before
```yaml
from_school:
  - route_name: "주중(14시 10분)"
    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
    arrival_info:
      - node_name: *koreatech
        arrival_time: "14:10"
      - node_name: *campus_2
        arrival_time: "14:35"
      - node_name: *terminal
        arrival_time: "14:42"
      - node_name: *cheonan_station
        arrival_time: "14:47"
      - node_name: *koreatech
        arrival_time: "15:15"
        
  - route_name: "주중(20시)"
    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
    arrival_info:
      - node_name: *koreatech
        arrival_time: "20:00"
      - node_name: *terminal
        arrival_time: "20:25"
      - node_name: *cheonan_station
        arrival_time: "20:30"
      - node_name: *koreatech
        arrival_time: "21:00"
```

**After**
```yaml
nodes:
  - &samryong_bridge "삼룡교(유니클로, 구 한방병원)"
  - &baro_pharmacy "바로약국 앞"

from_school:
  - route_name: "주중(14시 10분)"
    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
    arrival_info:
      - node_name: *koreatech
        arrival_time: "14:10"
      - node_name: *terminal
        arrival_time: "14:35"
      - node_name: *cheonan_station
        arrival_time: "14:40"
      - node_name: *samryong_bridge
        arrival_time: "14:45"
      - node_name: *baro_pharmacy
        arrival_time: "14:48"
      - node_name: *koreatech
        arrival_time: "15:15"

  - route_name: "주중(20시 30분)"
    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
    arrival_info:
      - node_name: *koreatech
        arrival_time: "20:30"
      - node_name: *terminal
        arrival_time: "20:55"
      - node_name: *cheonan_station
        arrival_time: "21:00"
      - node_name: *koreatech
        arrival_time: "21:30"
```

**Comment by daheeParkk** [comment]
변경 내용

1. 서울 등교/하교
**등교**
변경 전> 월요일 (07시10분, 07시30분), 월요일 ~ 금요일 (07시20분)
변경 후> 월요일 ~ 금요일 (07시20분)
**하교**
변경 전> 금요일 (14시10분), 수요일추가배차 (16시10분), 월요일 ~ 금요일 (18시10분)
변경 후> 월요일 ~ 금요일 (18시10분)

2. 대전 등교/하교
**등교**
변경 전> 일요일(18시10분, 18시20분)
변경 후> 일요일(18시20분)
**하교**
변경 전> 금요일(14시, 18시20분), 수요일추가배차(18시10분)
변경 후> 금요일(18시20분)

### 서울 등교/하교
변경 전
```yaml
to_school:
  - route_name: "월요일 (07시10분)"
    running_days: [ "MON" ]
    arrival_info:
      - node_name: *seoul_gyodae_station
        arrival_time: "07:10"
      - node_name: *koreatech
        arrival_time: "08:40"

  - route_name: "월요일(07시30분)"
    running_days: [ "MON" ]
    arrival_info:
      - node_name: *dongcheon_station
        arrival_time: "07:30"
      - node_name: *jukjeon_simple_station
        arrival_time: "07:33"
      - node_name: *koreatech
        arrival_time: "08:40"

  - route_name: "월요일~금요일 (07시20분)"
    running_days: [ "MON", "TUE", "WED", "THU", "FRI" ]
    arrival_info:
      - node_name: *seoul_gyodae_station
        arrival_time: "07:20"
      - node_name: *dongcheon_station
        arrival_time: "07:37"
      - node_name: *jukjeon_simple_station
        arrival_time: "07:40"
      - node_name: *koreatech
        arrival_time: "08:50"

from_school:
  - route_name: "금요일 (14시10분)"
    running_days: [ "FRI" ]
    arrival_info:
      - node_name: *koreatech
        arrival_time: "14:10"
      - node_name: *jukjeon_simple_station
        arrival_time: "하차"
      - node_name: *seoul_gyodae_station
        arrival_time: "하차"

  - route_name: "수요일추가배차 (16시10분)"
    running_days: [ "WED" ]
    arrival_info:
      - node_name: *koreatech
        arrival_time: "16:10"
      - node_name: *jukjeon_simple_station
        arrival_time: "하차"
      - node_name: *seoul_gyodae_station
        arrival_time: "하차"

  - route_name: "월요일~금요일 (18시10분)"
    running_days: [ "MON", "TUE", "WED", "THU", "FRI" ]
    arrival_info:
      - node_name: *koreatech
        arrival_time: "18:10"
      - node_name: *jukjeon_simple_station
        arrival_time: "하차"
      - node_name: *seoul_gyodae_station
        arrival_time: "하차"
```
변경 후
```yaml
to_school:
  - route_name: "월요일~금요일 (07시20분)"
    running_days: [ "MON", "TUE", "WED", "THU", "FRI" ]
    arrival_info:
      - node_name: *seoul_gyodae_station
        arrival_time: "07:20"
      - node_name: *dongcheon_station
        arrival_time: "07:37"
      - node_name: *jukjeon_simple_station
        arrival_time: "07:40"
      - node_name: *koreatech
        arrival_time: "08:50"

from_school:
  - route_name: "월요일~금요일 (18시10분)"
    running_days: [ "MON", "TUE", "WED", "THU", "FRI" ]
    arrival_info:
      - node_name: *koreatech
        arrival_time: "18:10"
      - node_name: *jukjeon_simple_station
        arrival_time: "하차"
      - node_name: *seoul_gyodae_station
        arrival_time: "하차"
```

### 대전 등교/하교
변경 전
```yaml
to_school:
  - route_name: "일요일(18시10분)"
    running_days: ["SUN"]
    arrival_info:
      - node_name: *daejeon_station
        arrival_time: "18:10"
      - node_name: *compound_terminal
        arrival_time: "18:15"
      - node_name: *koreatech
        arrival_time: "하차"

  - route_name: "일요일(18시20분)"
    running_days: [ "SUN" ]
    arrival_info:
      - node_name: *daejeon_station
        arrival_time: "18:20"
      - node_name: *compound_terminal
        arrival_time: "하차"
      - node_name: *koreatech
        arrival_time: "하차"


from_school:
 - route_name: "금요일(14시)"
   running_days: ["FRI"]
   arrival_info:
     - node_name: *koreatech
       arrival_time: "14:00"
     - node_name: *compound_terminal
       arrival_time: "하차"
     - node_name: *daejeon_station
       arrival_time: "하차"

  - route_name: "금요일(18시20분)"
    running_days: ["FRI"]
    arrival_info:
      - node_name: *koreatech
        arrival_time: "18:20"
      - node_name: *compound_terminal
        arrival_time: "하차"
      - node_name: *daejeon_station
        arrival_time: "하차"

  - route_name: "수요일추가배차(18시10분)"
    running_days: ["WED"]
    arrival_info:
      - node_name: *koreatech
        arrival_time: "18:10"
      - node_name: *compound_terminal
        arrival_time: "하차"
      - node_name: *daejeon_station
        arrival_time: "하차"
```

변경 후
```yaml
to_school:
  - route_name: "일요일(18시20분)"
    running_days: [ "SUN" ]
    arrival_info:
      - node_name: *daejeon_station
        arrival_time: "18:20"
      - node_name: *compound_terminal
        arrival_time: "하차"
      - node_name: *koreatech
        arrival_time: "하차"


from_school:
  - route_name: "금요일(18시20분)"
    running_days: ["FRI"]
    arrival_info:
      - node_name: *koreatech
        arrival_time: "18:20"
      - node_name: *compound_terminal
        arrival_time: "하차"
      - node_name: *daejeon_station
        arrival_time: "하차"
```

**Comment by daheeParkk** [comment]
### 청주 셔틀 
**등교** 
빈 배열로 반환하도록 변경

```yaml
to_school:
  - route_name: "미운행"
    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
    arrival_info: []
```
