### ISSUE TITLE
230401 셔틀버스 시간 변경

### ISSUE THREAD

**Issue by Invidam** [BCSDLab/KOIN_BATCH#9]
기존:
https://www.koreatech.ac.kr/kor/CMS/NoticeMgr/view.do?mCode=MN230&post_seq=30319&board_id=14

4/1부터 변경:
https://www.koreatech.ac.kr/kor/CMS/NoticeMgr/view.do?mCode=MN230&post_seq=30480&board_id=14

**Comment by Invidam** [comment]
**예시**


**바꾼 내용**
5번 일학습 병행제 추가

**파일 명**
cheonan_commutiong.yaml

**파일 내용**

```
{
}
```

**Comment by Invidam** [comment]
**바꾼 내용**
3. 아산/KTX 셔틀 삭제 
<br>

**파일 명**
cheoan_shuttle.yaml

**변경 전**
  - route_name: "주중(10시50분)"
    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
    arrival_info:
      - node_name: *koreatech
        arrival_time: "10:50"
      - node_name: *ktx_exit_3
        arrival_time: "11:25"
      - node_name: *koreatech
        arrival_time: "11:50"
 
<br>
**변경 후**
#  - route_name: "주중(10시50분)"
#    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
#    arrival_info:
#      - node_name: *koreatech
#        arrival_time: "10:50"
#      - node_name: *ktx_exit_3
#        arrival_time: "11:25"
#      - node_name: *koreatech
#        arrival_time: "11:50"

**Comment by tmdgus1715** [comment]
바꾼 내용
3. 아산/KTX 셔틀 삭제


파일 명
cheoan_shuttle.yaml

변경 전

route_name: "주중(10시50분)"
running_days: ["MON", "TUE", "WED", "THU", "FRI"]
arrival_info:
node_name: *koreatech
arrival_time: "10:50"
node_name: *ktx_exit_3
arrival_time: "11:25"
node_name: *koreatech
arrival_time: "11:50"

**변경 후** 
<br>
#  - route_name: "주중(10시50분)"
#    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
#    arrival_info:
#      - node_name: *koreatech
#        arrival_time: "10:50"
#      - node_name: *ktx_exit_3
#        arrival_time: "11:25"
#      - node_name: *koreatech
#        arrival_time: "11:50"

**Comment by Invidam** [comment]
> 바꾼 내용 3. 아산/KTX 셔틀 삭제
- 확인 완료
- 스테이지에 갱신 완료

**Comment by songsunkook** [comment]
**바꾼 내용**
2. 아산/KTX 노선 – 시간 변경

**파일 명**
cheonan_commuting.yaml

변경 전
```
  - route_name: "아산/KTX"
    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
    arrival_info:
      - node_name: *onyang
        arrival_time: "07:15"
      - node_name: *baebang
        arrival_time: "07:30"
      - node_name: *hoseo
        arrival_time: "07:40"
```

**변경 후**
```
  - route_name: "아산/KTX"
    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
    arrival_info:
      - node_name: *onyang
        arrival_time: "07:20"
      - node_name: *baebang
        arrival_time: "07:35"
      - node_name: *hoseo
        arrival_time: "07:45"
```

**Comment by Invidam** [comment]
> **바꾼 내용** 2. 아산/KTX 노선 – 시간 변경
> 
> **파일 명** cheonan_commuting.yaml
> 
> 변경 전
> 
> ```
>   - route_name: "아산/KTX"
>     running_days: ["MON", "TUE", "WED", "THU", "FRI"]
>     arrival_info:
>       - node_name: *onyang
>         arrival_time: "07:15"
>       - node_name: *baebang
>         arrival_time: "07:30"
>       - node_name: *hoseo
>         arrival_time: "07:40"
> ```
> 
> **변경 후**
> 
> ```
>   - route_name: "아산/KTX"
>     running_days: ["MON", "TUE", "WED", "THU", "FRI"]
>     arrival_info:
>       - node_name: *onyang
>         arrival_time: "07:20"
>       - node_name: *baebang
>         arrival_time: "07:35"
>       - node_name: *hoseo
>         arrival_time: "07:45"
> ```

- 확인 완료
- 1번 내용이랑 같이 올려야 해서 스테이지에 올릴 예정

**Comment by Invidam** [comment]
바꾼 내용 1. 천안역 노선 – 노선 변경

파일 명 cheonan_commuting.yaml

변경 전
`to_school:
  - route_name: "천안역"
    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
    arrival_info:
      - node_name: *cheonan_station
        arrival_time: "08:10"
      - node_name: *nambu
        arrival_time: "08:12"
      - node_name: *samryong
        arrival_time: "08:15"
      - node_name: *baro
        arrival_time: "08:16"
      - node_name: *dongwoo
        arrival_time: "승하차"
      - node_name: *joongang
        arrival_time: "승하차"
      - node_name: *koreatech
        arrival_time: "08:50"

from_school:
  - route_name: "천안역"
    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
    arrival_info:
      - node_name: *koreatech
        arrival_time: "18:10"
      - node_name: *joongang
        arrival_time: "승하차"
      - node_name: *dongwoo
        arrival_time: "승하차"
      - node_name: *baro
        arrival_time: "18:44"
      - node_name: *samryong
        arrival_time: "18:45"
      - node_name: *nambu
        arrival_time: "18:48"
      - node_name: *cheonan_station
        arrival_time: "18:50"

`
변경 후 
`
  - &hanyang "한양 수자인BS"
  
to_school:
  - route_name: "천안역"
    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
    arrival_info:
      - node_name: *cheonan_station
        arrival_time: "08:10"
      - node_name: *hanyang
        arrival_time: "08:18"
      - node_name: *chungdang
        arrival_time: "08:21"
      - node_name: *dongwoo
        arrival_time: "승하차"
      - node_name: *joongang
        arrival_time: "승하차"
      - node_name: *koreatech
        arrival_time: "08:50"

from_school:
  - route_name: "천안역"
    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
    arrival_info:
      - node_name: *koreatech
        arrival_time: "18:10"
      - node_name: *joongang
        arrival_time: "승하차"
      - node_name: *dongwoo
        arrival_time: "승하차"
      - node_name: *chungdang
        arrival_time: "18:39"
      - node_name: *hanyang
        arrival_time: "18:42"
      - node_name: *cheonan_station
        arrival_time: "18:50"

**Comment by johnny19991006** [comment]
변경 내용
  - route_name: "월요일(07시 30분)"
    runnung_days: ["MON"]
    arrival_info:
      - node_name: *dongcheon_station
        arrival_time: "07:30"
      - node_name: *jukjeon_simple_station
        arrival_time: "07:33"
      - node_name: *koreatech
        arrival_time: "08:40"


  - route_name: "월요일~금요일 (07시20분)"
    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
    arrival_info:
      - node_name: *seoul_gyodae_station
        arrival_time: "07:20"
      - node_name: *dongcheon_station
        arrival_time: "07:37"
      - node_name: *jukjeon_simple_station
        arrival_time: "07:40"
      - node_name: *koreatech
        arrival_time: "08:50"

**Comment by Invidam** [comment]
` ```  내용  ``` ` 이런식으로 감싸야 함

**Comment by Invidam** [comment]
> 바꾼 내용 1. 천안역 노선 – 노선 변경
> 
> 파일 명 cheonan_commuting.yaml
> 
> 변경 전
> 
> ```
> to_school:
>   - route_name: "천안역"
>     running_days: ["MON", "TUE", "WED", "THU", "FRI"]
>     arrival_info:
>       - node_name: *cheonan_station
>         arrival_time: "08:10"
>       - node_name: *nambu
>         arrival_time: "08:12"
>       - node_name: *samryong
>         arrival_time: "08:15"
>       - node_name: *baro
>         arrival_time: "08:16"
>       - node_name: *dongwoo
>         arrival_time: "승하차"
>       - node_name: *joongang
>         arrival_time: "승하차"
>       - node_name: *koreatech
>         arrival_time: "08:50"
> 
> from_school:
>   - route_name: "천안역"
>     running_days: ["MON", "TUE", "WED", "THU", "FRI"]
>     arrival_info:
>       - node_name: *koreatech
>         arrival_time: "18:10"
>       - node_name: *joongang
>         arrival_time: "승하차"
>       - node_name: *dongwoo
>         arrival_time: "승하차"
>       - node_name: *baro
>         arrival_time: "18:44"
>       - node_name: *samryong
>         arrival_time: "18:45"
>       - node_name: *nambu
>         arrival_time: "18:48"
>       - node_name: *cheonan_station
>         arrival_time: "18:50"
> ```
> 
> 변경 후
> 
> ```
>   - &hanyang "한양 수자인BS"
>   
> to_school:
>   - route_name: "천안역"
>     running_days: ["MON", "TUE", "WED", "THU", "FRI"]
>     arrival_info:
>       - node_name: *cheonan_station
>         arrival_time: "08:10"
>       - node_name: *hanyang
>         arrival_time: "08:18"
>       - node_name: *chungdang
>         arrival_time: "08:21"
>       - node_name: *dongwoo
>         arrival_time: "승하차"
>       - node_name: *joongang
>         arrival_time: "승하차"
>       - node_name: *koreatech
>         arrival_time: "08:50"
> 
> from_school:
>   - route_name: "천안역"
>     running_days: ["MON", "TUE", "WED", "THU", "FRI"]
>     arrival_info:
>       - node_name: *koreatech
>         arrival_time: "18:10"
>       - node_name: *joongang
>         arrival_time: "승하차"
>       - node_name: *dongwoo
>         arrival_time: "승하차"
>       - node_name: *chungdang
>         arrival_time: "18:39"
>       - node_name: *hanyang
>         arrival_time: "18:42"
>       - node_name: *cheonan_station
>         arrival_time: "18:50"
> ```

- 확인 완료
- 스테이지 갱신 완료

**Comment by Invidam** [comment]
> 변경 내용 서울셔틀
> 
> ```
>  - route_name: "월요일 (07시10분)"
>     running_days: ["MON"]
>     arrival_info:
>       - node_name: *seoul_gyodae_station
>         arrival_time: "07:10"
>        
>       - node_name: *koreatech
>         arrival_time: "08:40"
> 
> 
>   - route_name: "월요일(07시 30분)"
>     runnung_days: ["MON"]
>     arrival_info:
>       - node_name: *dongcheon_station
>         arrival_time: "07:30"
>       - node_name: *jukjeon_simple_station
>         arrival_time: "07:33"
>       - node_name: *koreatech
>         arrival_time: "08:40"
> ```

- 확인완료
- 하차도 변경해야 함

**Comment by songsunkook** [comment]
***바꾼 내용***
2. 아산/KTX 노선 – 시간 변경 ( 하교 )

***파일 명***
cheonan_commuting.yaml

변경 전
```yaml
  - route_name: "아산/KTX"
    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
    arrival_info:
    (생략)
      - node_name: *hoseo
        arrival_time: "19:20"
      - node_name: *baebang
        arrival_time: "19:30"
      - node_name: *onyang
        arrival_time: "19:45"
```

**변경 후**
```yaml
  - route_name: "아산/KTX"
    running_days: ["MON", "TUE", "WED", "THU", "FRI"]
    arrival_info:
    (생략)
      - node_name: *hoseo
        arrival_time: "19:15"
      - node_name: *baebang
        arrival_time: "19:25"
      - node_name: *onyang
        arrival_time: "19:40"
```
